VotingProject/urls.py
from django.contrib import admin
from django.urls import include, path
from VotingProject import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('votinghome/', include('votinghome.urls')),
    path("",views.index,name="index"),
    path("register",views.register,name="register"),
    path("user_login",views.user_login,name="user_login"),
    path("user_dashboard",views.user_dashboard,name="user_dashboard"),
    path("user_logout",views.user_logout,name="user_logout"),
    path('success',views.success,name="success"),
    path('voter_register',views.voter_register,name="voter_register"),
    path("trail",views.trail,name="trail"),
    path('test2',views.test2,name='test2'),
    path('voter_login',views.voter_login,name="voter_login"),
    path('org_login',views.org_login,name="org_login"),
    path('admin_login',views.admin_login,name="admin_login"),
    path('<str:voter_id>/voter_dashboard',views.voter_dashboard,name="voter_dashboard"),
    path('org_register',views.org_register,name="org_register"),\
    path('admin_dashboard',views.admin_dashboard,name='admin_dashboard'),
    path('<str:org_name>/org_dashboard/',views.org_dashboard,name='org_dashboard'),
    path('<str:org_name>/create_poll/',views.create_poll,name='create_poll'),
    path('<str:org_name>/org_vote_view/<str:poll_id>/',views.org_vote_view,name='org_vote_view'),
    path('<str:org_name>/manage_poll_list/',views.manage_poll_list,name='manage_poll_list'),
    path('<str:org_name>/voter_list/',views.voter_list,name='voter_list'),
    path('<str:org_name>/poll/<int:poll_id>/results/', views.poll_results, name='poll_results'),
    path('<str:org_name>/edit_poll/<int:poll_id>/', views.edit_poll, name='edit_poll'),
    path('<str:org_name>/profile/', views.org_profile_view, name='org_profile'),
    
    ## voter urls
    path('<str:voter_id>/voter_dashboard',views.voter_dashboard,name="voter_dashboard"),
    path('<str:voter_id>/active_polls_list/', views.active_polls_list, name="active_polls_list"),
    path('<str:voter_id>/<int:poll_id>/', views.vote_poll, name='vote_poll'),
    path('<str:voter_id>/poll_results/<int:poll_id>/', views.voter_poll_results, name='voter_poll_results'),
 

]

votinghome/urls.py
from django.contrib import admin
from django.urls import include, path
from votinghome import views
urlpatterns = [

path('', views.home, name='home'),



]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User

class Organization(models.Model):
    name = models.CharField(max_length=100)
    admin = models.OneToOneField(User, on_delete=models.CASCADE)
    role = models.CharField(max_length=100)
    id_number = models.CharField(max_length=100, blank=True, null=True)
    department = models.CharField(max_length=100, blank=True, null=True)
    

    def __str__(self):
        return self.name

class Voter(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    organization = models.ForeignKey(Organization, on_delete=models.CASCADE)
    aadhar_number = models.CharField(max_length=16, unique=True, null=True)
    role = models.CharField(max_length=100)
    id_number = models.CharField(max_length=100, blank=True, null=True)
    department = models.CharField(max_length=100, blank=True, null=True)
   

    def __str__(self):
        return self.user.username

class Poll(models.Model):
    question = models.CharField(max_length=255)
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()
    admin = models.ForeignKey(User, on_delete=models.CASCADE)
    stopped = models.BooleanField(default=False) 

    def __str__(self):
        return self.question

class Choice(models.Model):
    poll = models.ForeignKey(Poll, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=100)

    def __str__(self):
        return self.choice_text

class PollVote(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    poll = models.ForeignKey(Poll, on_delete=models.CASCADE)
    choice = models.ForeignKey(Choice, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.user.username} voted for {self.choice.choice_text}"

templates/voter/active_polls.html
{% extends 'voter/voter_base.html' %} 
{% load static %}
{% block title %}Active Polls {% endblock %}  
<link href="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/css/bootstrap-combined.no-icons.min.css" rel="stylesheet">
<link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet">

{% block content %}


<style>
  table {
    font-family: arial, sans-serif;
    border-collapse: collapse;
    width: 100%;
  }

  td,
  th {
    border: 1px solid #dddddd;
    text-align: left;
    padding: 8px;
  }

  tr:nth-child(even) {
    background-color: #dddddd;
  }
</style>

  <h1 style="text-align:center">Active Polls</h1>
  {% if messages %}
    {% for message in messages %}
        <div class="alert {% if message.tags == 'error' %}alert-danger{% elif message.tags == 'success' %}alert-success{% endif %} alert-dismissible fade show" role="alert">
            {{ message }}
           
        </div>
    {% endfor %}
{% endif %}
  <div class="container">
      <div class="container">

      </div>
  <table class="table table-hover">
    <tr>
      <th>S.No</th>
      <th>Poll's</th>
      <th>Action</th>
    </tr>

    {% for poll in active_polls %}
    </tr>
    <td>{{ forloop.counter}}</td>
    <td>{{ poll.question }}</td>
    <td><a href="{% url 'vote_poll' voter_id=voter.id poll_id=poll.id %}" class="btn btn-warning"><i class='fas fa-vote-yea' ></i>Vote</a>
    &nbsp; | &nbsp; <a href="{% url 'voter_poll_results' voter_id=voter.id poll_id=poll.id %}" class="btn btn-success"><i class='fas fa-vote-yea' ></i>Results</a>
  </td>
      </tr>
    {% endfor %}

  </table>
  </div>

{% endblock %}

templates/voter/poll_voting.html
{% extends 'voter/voter_base.html' %}
{% load static %}
{% block title %}Vote in Poll {% endblock %}
{% block content %}
<div class="container">

  {% if not already_voted %}
  <h1 style="text-align: center; margin-top: 20px">Vote in Poll</h1>
  <div class="row justify-content-center">
    <div class="col-md-6">
      <form method="POST" action="{% url 'vote_poll' voter_id=voter.id poll_id=poll.id %}">
        {% csrf_token %}
        <div class="mb-3">
          <label for="poll_question" class="form-label">Poll Question:</label>
          <input type="text" class="form-control" id="poll_question" value="{{ poll.question }}" readonly />
        </div>
        <div class="mb-3">
          <label for="choices" class="form-label">Select your choice:</label>
          {% for choice in poll.choice_set.all %}
          <div class="form-check">
            <input class="form-check-input" type="radio" name="choice" id="choice{{ choice.id }}" value="{{ choice.id }}" required>
            <label class="form-check-label" for="choice{{ choice.id }}">{{ choice.choice_text }}</label>
          </div>
          {% endfor %}
        </div>
        <center>
          <button type="submit" class="btn btn-success">Vote</button>
        </center>
      </form>
      {% else %}
     
      {% endif %}
      
       <div class="container" style="margin-top:150px;text-align:center">
{% if messages %}
    {% for message in messages %}
        <div class="alert {% if message.tags == 'error' %}alert-danger{% elif message.tags == 'success' %}alert-success{% endif %} alert-dismissible fade show" role="alert">
            {{ message }}
           
        </div>
    {% endfor %}
{% endif %}

</div>
    </div>
  </div>
</div>
{% endblock %}

templates/voter/voter_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
    />
    <link
      href="https://getbootstrap.com/docs/5.3/assets/css/docs.css"
      rel="stylesheet"
    />
    <title>{{ voter.user.username }} Dashboard</title>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
    <link
      rel="stylesheet"
      href="https://fonts.googleapis.com/css?family=Roboto"
    />
    <link rel="stylesheet" href="{% static 'assets/css/admin.css' %}" />
    <link
      href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css"
      rel="stylesheet"
    />
    <script
      src="https://kit.fontawesome.com/a076d05399.js"
      crossorigin="anonymous"
    ></script>
  </head>

  <body>
    <section>
      <nav
        class="navbar navbar-expand-lg bg-body-tertiary"
        data-bs-theme="dark"
        style="padding-top: 20px; padding-bottom: 20px"
      >
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'voter_dashboard' voter_id=voter.id %}"
            >{{ voter.user.first_name }} {{ voter.user.last_name }}</a
          >
          <button
            class="navbar-toggler"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#navbarNavDropdown"
            aria-controls="navbarNavDropdown"
            aria-expanded="false"
            aria-label="Toggle navigation"
          >
            <span class="navbar-toggler-icon"></span>
          </button>
          <div
            class="collapse navbar-collapse justify-content-between"
            id="navbarNavDropdown"
          >
            <ul class="navbar-nav">
              <li class="nav-item">
                <a
                  class="nav-link active"
                  aria-current="page"
                  href="{% url 'voter_dashboard' voter_id=voter.id %}"
                  >Dashboard</a
                >
              </li>
             
              <li class="nav-item dropdown">
                <a
                  class="nav-link dropdown-toggle"
                  href="#"
                  role="button"
                  data-bs-toggle="dropdown"
                  aria-expanded="false"
                >
                  Polls
                </a>
                <ul class="dropdown-menu dropdown-menu-dark">
                  <li>
                    <a class="dropdown-item" href="{% url 'active_polls_list' voter_id=voter.id %}">Active Polls</a>
                  </li>
                
                
                </ul>
              </li>
             
            </ul>
           
            <ul class="navbar-nav">
              <li class="nav-item dropdown">
                <a
                  class="nav-link dropdown-toggle"
                  href="#"
                  role="button"
                  data-bs-toggle="dropdown"
                  aria-expanded="false"
                  >Account Settings</a
                >
                <ul class="dropdown-menu dropdown-menu-end dropdown-menu-dark">
                  <li>
                    <a class="dropdown-item" href="{% url 'user_logout' %}"
                      ><i class="fa fa-sign-out" aria-hidden="true"></i>
                      &nbsp;Logout</a
                    >
                  </li>
                
                 
                </ul>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    </section>
    {% block content %}{% endblock %}
  </body>
</html>

templates/voter/voter_dashboard.html
{% extends 'voter/voter_base.html' %}

{% block title %}
  {{ voter.user.username }} Dashboard
{% endblock %}

{% block content %}
  <div class="container">
    <div class="card bg-secondary text-white">
    <div class="card-body">
      <h1 class="card-success">Welcome to {{ voter.user.username }}'s Dashboard!</h1>
    </div>
  </div>   
    <div class="card">
      <div class="card-header">
        <h2>Voter Information</h2>
      </div>
      <div class="card-body">
        <p><strong>Name:</strong> {{ voter.user.get_full_name }}</p>
        <p><strong>Username:</strong> {{ voter.user.username }}</p>
        <p><strong>Email:</strong> {{ voter.user.email }}</p>
        <p><strong>Organization:</strong> {{ voter.organization.name }}</p>
       
      </div>
    </div>


    <div class="card mt-3">
      <div class="card-header">
        <h2>Recent Votes</h2>
      </div>
      <div class="card-body">
        <ul>
          {% for vote in recent_votes %}
            <li>{{ vote }}</li>
          {% endfor %}
        </ul>
      </div>
    </div>

   
  </div>
{% endblock %}

templates/voter/voter_poll_results.html
{% extends 'voter/voter_base.html' %}

{% block title %}Poll Results{% endblock %}

{% block content %}
<div class="container">
  <h1 class="text-center">{{ poll.question }}</h1>


  {% if voted_choice %}
  <div class="alert alert-info" role="alert">
    You have casted your vote for: <strong>{{ voted_choice }}</strong>
  </div>
  {% endif %}

 
  <div class="chart-container">
    <canvas id="pollChart" width="100" height="25"></canvas>
  </div>


  <table class="table table-bordered">
    <thead>
      <tr>
        <th>Choice</th>
        <th>Votes Count</th>
      </tr>
    </thead>
    <tbody>
      {% for choice, count in results.items %}
      <tr>
        <td>{{ choice }}</td>
        <td>{{ count }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>

<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script>

  var ctx = document.getElementById('pollChart').getContext('2d');
  var data = {
    labels: [{% for choice, count in results.items %}"{{ choice }}",{% endfor %}],
    datasets: [{
      label: 'Poll Results',
      data: [{% for choice, count in results.items %}{{ count }},{% endfor %}],
      backgroundColor: [
        'rgba(255, 99, 132, 0.2)',
        'rgba(54, 162, 235, 0.2)',
        'rgba(255, 206, 86, 0.2)',
        'rgba(75, 192, 192, 0.2)',
        'rgba(153, 102, 255, 0.2)',
        'rgba(255, 159, 64, 0.2)'
      ],
      borderColor: [
        'rgba(255, 99, 132, 1)',
        'rgba(54, 162, 235, 1)',
        'rgba(255, 206, 86, 1)',
        'rgba(75, 192, 192, 1)',
        'rgba(153, 102, 255, 1)',
        'rgba(255, 159, 64, 1)'
      ],
      borderWidth: 1
    }]
  };
  var options = {
    scales: {
      yAxes: [{
        ticks: {
          beginAtZero: true
        }
      }]
    }
  };
  var myChart = new Chart(ctx, {
    type: 'bar',
    data: data,
    options: options
  });
</script>
{% endblock %}